async(page)=>{
  const results=[],errors=[],base='http://127.0.0.1:8765/docs/';page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.emulateMedia({reducedMotion:'reduce'});
  const assert=(v,msg)=>{if(!v)throw Error(msg);};
  const seed=async(phase,mission,extras={})=>{await page.evaluate(({phase,mission,extras})=>{const s=fresh();s.phase=phase;s.mission=mission;s.last='living';s.quests.forEach((q,i)=>q.verified=i<mission);Object.assign(s,extras);localStorage.setItem('iris-birthday-quest-v3',JSON.stringify(s));},{phase,mission,extras});await page.reload();};
  await seed('mission',1);await page.setViewportSize({width:1200,height:1200});await page.evaluate(()=>{state.quests[1].step=1;state.quests[1].powers=[2,1,4,3];save();render();});await page.locator('#ingredient-pool').scrollIntoViewIfNeeded();
  const ingredient=await page.locator('[data-action="pour"][data-value="A"]').boundingBox(),drop=await page.locator('#cauldron-drop').boundingBox();
  await page.mouse.move(ingredient.x+ingredient.width/2,ingredient.y+ingredient.height/2);await page.mouse.down();await page.waitForTimeout(220);await page.mouse.move(drop.x+drop.width/2,drop.y+drop.height/2,{steps:20});await page.waitForTimeout(180);await page.mouse.up();await page.waitForTimeout(100);assert((await page.evaluate(()=>state.quests[1].brew)).includes('A'),'real potion drag failed');results.push('Sortable potion drag: PASS');
  await seed('mission',3);
  await page.evaluate(()=>{window.cameraRequests=0;navigator.mediaDevices.getUserMedia=async()=>{cameraRequests++;throw new DOMException('Denied','NotAllowedError');};});assert(await page.evaluate(()=>cameraRequests)===0,'camera requested on load');
  await page.locator('[data-hardware="camera"]').click();await page.waitForFunction(()=>document.querySelector('#hardware-dialog .hardware-status')?.textContent.includes('没有开启'),null,{timeout:60000});assert(await page.evaluate(()=>cameraRequests)===1,'local model failed before permission');await page.locator('#hardware-dialog [data-hardware="close"]').first().click();results.push('actual local MediaPipe load and denied camera fallback: PASS');
  await page.evaluate(()=>{const c=document.createElement('canvas');c.width=640;c.height=480;const x=c.getContext('2d');x.fillStyle='#253c53';x.fillRect(0,0,640,480);const stream=c.captureStream(12);window.cameraTrack=stream.getTracks()[0];window.qaCameraCanvas=c;window.paintCamera=setInterval(()=>{x.fillRect(0,0,640,480);},80);navigator.mediaDevices.getUserMedia=async()=>stream;});
  await page.locator('[data-hardware="camera"]').click();await page.waitForFunction(()=>document.querySelector('#hardware-dialog .hardware-status')?.textContent.startsWith('摄像头已开启'),null,{timeout:20000});await page.waitForTimeout(300);await page.locator('#hardware-dialog [data-hardware="close"]').first().click();assert(await page.evaluate(()=>cameraTrack.readyState)==='ended','camera track leaked');await page.evaluate(()=>clearInterval(paintCamera));results.push('granted video stream, live model loop and camera cleanup: PASS');
  await seed('memory',4,{memoryIndex:3});
  await page.evaluate(()=>{window.sensorRequests=0;window.sensorListeners=0;DeviceOrientationEvent.requestPermission=async()=>{sensorRequests++;return 'granted';};const add=window.addEventListener.bind(window),remove=window.removeEventListener.bind(window);window.addEventListener=(name,...args)=>{if(name==='deviceorientation')sensorListeners++;return add(name,...args);};window.removeEventListener=(name,...args)=>{if(name==='deviceorientation')sensorListeners--;return remove(name,...args);};});
  await page.locator('[data-hardware="pensieve"]').click();await page.waitForFunction(()=>document.querySelector('.pensieve-caption')?.textContent==='六根银丝，藏着属于我们的时刻。');assert(await page.evaluate(()=>sensorRequests)===0,'sensor requested on entry');await page.locator('[data-memory-thread="0"]').click();await page.locator('[data-sensor]').click();assert(await page.evaluate(()=>sensorRequests===1&&sensorListeners===1),'sensor activation failed');
  await page.evaluate(()=>{const event=new Event('deviceorientation');Object.assign(event,{alpha:10,beta:70,gamma:0});dispatchEvent(event);});await page.locator('#hardware-dialog [data-hardware="close"]').click();assert(await page.evaluate(()=>sensorListeners)===0,'sensor listener leaked');results.push('explicit orientation permission and listener cleanup: PASS');
  for(const width of [320,390,430,768,1200]){await page.setViewportSize({width,height:900});for(const [phase,mission,extra]of [['memory',4,{memoryIndex:3}],['end',6,{endStage:0}],['end',6,{endStage:1}],['end',6,{endStage:2}]]){await seed(phase,mission,extra);assert(!(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1)),`new scene overflow: ${width}/${phase}/${extra.endStage}`);}}
  results.push('20 new responsive memory/finale scenes: PASS');assert(errors.length===0,errors.join('; '));return{results,errors};
}
